### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by trondhindenes** [bgelens/WAPTenantPublicAPI#1]
Hi Ben, 
Just a small suggestion regarding PS modules where some kind of session/token is used: 
In order to make it easy on the user, I often prefer to create a "Connect-*" function which simply stores the required session info in a variable, and then just use those vars in the actual functions. IMHO this provides a better flow instead of having to (essentially) provide session info with each script function called. I talked briefly about this in my session during last years PowerShell summit, and there are some example files online here:
http://hindenes.com/trondsworking/wp-content/uploads/2014/04/PowerShell-Summit-2014.zip

If you unzip and navigate to modules\webapifunctionV2\webapifunctionv2.psm1 you'll see a simple example of what I mean ("Connect-ServerDB"). In that example I use two variables, $Mdauthheader (for the bearer token) and $mdwebapiurl (for the web api url).

Just a thought :-)

**Comment by bgelens** [comment]
Hi Trond,
Thanks for the feedback! I actually was considering using scoped variables for this but decided not to because I got the feeling there is a lot of resistence against them. I still have a lot of work to do on this module, so I'll see if I reconsider. It would be a lot cleaner that's for sure :) For now I'm just trying to stabilize it as much as posible so I can use it as the basis for a DSC resource.

Question though, in this case I have 2 systems to connect to, ADFS or ASP STS for the token and the WAP Api. Would you create 2 connect functions?

**Comment by bgelens** [comment]
Reconsidered and will go for module scoped variables in next release. In progress :-)

**Comment by bgelens** [comment]
Hi Trond, I refactored everything to work with module scoped variables. It removes a lot of the overhead on the Objects :-)
